/* THIS FILE WAS GENERATED BY PAYLOAD. */
import config from "@payload-config";
import { RootPage, generatePageMetadata } from "@payloadcms/next/views";
import { importMap } from "../importMap";

type Args = {
  params: Promise<{
    segments: string[];
  }>;
  searchParams: Promise<{
    [key: string]: string | string[];
  }>;
};

export const dynamic = "force-dynamic";

export default function AdminPage(args: Args) {
  return RootPage({
    ...args,
    config,
    importMap,
  });
}

export const generateMetadata = async (args: Args) => generatePageMetadata({ config, ...args });
